# Generated by Django 4.0.3 on 2022-04-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('client_mail', models.CharField(max_length=50, verbose_name='Почта пользователя')),
                ('client_object', models.CharField(max_length=200, verbose_name='Объект пользователя')),
                ('client_text', models.CharField(max_length=200, verbose_name='Сообщение пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_url', models.CharField(max_length=200, verbose_name='Ссылка меню')),
                ('menu_text', models.CharField(max_length=50, verbose_name='Текст меню')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_url', models.CharField(max_length=200, verbose_name='Ссылка слайдера')),
                ('slider_queue', models.IntegerField(verbose_name='Очередь слайда')),
                ('slider_delay', models.IntegerField(verbose_name='Задержка слайда')),
            ],
        ),
    ]
