# Generated by Django 4.0.3 on 2022-04-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_client_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_object',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_text',
        ),
    ]
