# Generated by Django 4.0.3 on 2022-04-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_client_client_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_mail',
            field=models.CharField(max_length=50, null=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес договора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_object',
            field=models.CharField(max_length=200, null=True, verbose_name='Объект договора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_text',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст договора'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_url',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка слайдера'),
        ),
    ]
