# Generated by Django 4.0.3 on 2022-05-08 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_client_client_mail_alter_client_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_mail',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта пользователя'),
        ),
        migrations.CreateModel(
            name='RequestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_file', models.FileField(max_length=254, upload_to=home.models.RequestUser.order_directory_path)),
                ('request_message', models.CharField(max_length=200, verbose_name='Сообщение заявления')),
                ('type_request', models.CharField(choices=[('1', 'Получение технических условий'), ('2', 'Заключение договора о подключении')], max_length=1, verbose_name='Тип заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
