# Generated by Django 4.0.3 on 2022-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_client_client_mail_requestuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
