# Generated by Django 4.0.3 on 2022-05-08 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_requestuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='requestuser',
            name='type_status',
            field=models.CharField(choices=[('1', 'На рассмотрении'), ('2', 'В работе'), ('3', 'В Исполнено'), ('4', 'Не принята в работу')], default='1', max_length=1, verbose_name='Статус заявки'),
        ),
    ]
