# Generated by Django 4.0.3 on 2022-05-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_requestuser_date_requestuser_type_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestuser',
            name='request_message',
            field=models.TextField(max_length=200, verbose_name='Сообщение заявления'),
        ),
    ]
