# Generated by Django 4.0.3 on 2022-05-14 09:29

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=200, verbose_name='Текст комментария')),
                ('comment_name', models.CharField(max_length=50, verbose_name='Автор комментария')),
                ('comment_email', models.EmailField(max_length=50, verbose_name='Почта автора комментария')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.FileField(upload_to=articles.models.Article.articles_directory_path)),
                ('article_title', models.CharField(max_length=200, verbose_name='Заглавие статьи')),
                ('article_date', models.DateTimeField(max_length=50, verbose_name='Дата статьи')),
                ('article_author', models.CharField(max_length=50, verbose_name='Автор статьи')),
                ('article_text', models.TextField(max_length=200, verbose_name='Текст статьи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
