# Generated by Django 4.0.3 on 2022-05-14 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment_article_alter_article_article_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная новость'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария'),
        ),
    ]
