# Generated by Django 4.0.3 on 2022-05-14 12:25

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_is_popular_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='icon_color',
            field=models.CharField(default=articles.models.Comment.get_random_color, max_length=50, verbose_name='Цвет иконки'),
        ),
    ]
